defaults:
  - graph_default
  - _self_

method_name: mipluxen

# Differences compared to paper
#       This repo                         mipLuxen
# density = softplus(x)          density = softplus(x-1)
# rgb = sigmoid(x)               rgb = (1 + 2e) / (1 + exp(-x)) -e

graph:
  _target_: pyrad.graphs.mipluxen.MipLuxenGraph
  num_coarse_samples: 128
  num_importance_samples: 128
  loss_coefficients:
    rgb_loss_coarse: 0.1
    rgb_loss_fine: 1.0
