defaults:
  - graph_default
  - _self_

experiment_name: friends_TBBT-big_living_room
method_name: luxenw

# the data
data:
  # Train dataloading.
  dataset_inputs_train:
    _target_: luxenactory.data.datasets.Friends
    data_directory: data/friends/TBBT-big_living_room
    downscale_factor: 1
  image_dataset_train:
    _target_: luxenactory.data.image_dataset.PanopticImageDataset
  # Eval dataloading
  dataset_inputs_eval:
    _target_: luxenactory.data.datasets.Friends
    data_directory: data/friends/TBBT-big_living_room
    downscale_factor: 1
  image_dataset_eval:
    _target_: luxenactory.data.image_dataset.PanopticImageDataset

graph:
  _target_: luxenactory.graphs.semantic_luxen.SemanticLuxenGraph
  collider_config:
    _target_: luxenactory.graphs.modules.scene_colliders.AABBBoxCollider
  num_coarse_samples: 64
  num_importance_samples: 64
  loss_coefficients:
    rgb_loss_coarse: 1.0
    rgb_loss_fine: 1.0
    semantic_loss_fine: 0.05
