defaults:
  - default_graph.yaml
  - _self_

network:
  _target_: radiance.luxen.graph.luxenw.LuxenWGraph
  loss_coefficients: # loss coefficients
    rgb_loss_coarse: 1.0
    rgb_loss_fine: 1.0
    uncertainty_loss: 1.0
    density_loss: 0.01
